name: Build Talal Falcon
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          rm -rf ~/theos
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Install ldid
        run: |
          # تحميل الأداة مباشرة من المصدر لضمان عملها
          sudo curl -Lo /usr/local/bin/ldid https://github.com/theos/ldid/releases/latest/download/ldid_macos_x86_64
          sudo chmod +x /usr/local/bin/ldid

      - name: Setup SDK
        run: |
          rm -rf ~/theos/sdks
          git clone https://github.com/theos/sdks.git ~/theos/sdks

      - name: Build Package
        run: |
          export THEOS=~/theos
          export PATH=$THEOS/bin:/usr/local/bin:$PATH
          make package FINALPACKAGE=1
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Talal-Falcon-App
          path: packages/*.deb
